### PR TITLE
Include .java files in the gemspec

### PR DESCRIPTION
**Pull request by darinwilson**
We wouldn't want to lose our lovely Java hacks in the generated gem file...

### CODE REVIEW

**Comment by GantMan** [comment]
woah :cat:

**Comment by jamonholmgren** [comment]
Can you write Java files and then just include them in `app.files` like that?

**Comment by darinwilson** [comment]
@jamonholmgren Yep - if you have a .java file next to a .rb file of the same name, the contents of the .java file are dumped into the Java class that RM creates for your Ruby class. 

http://www.rubymotion.com/developers/guides/manuals/android/project-management/#_extending_classes_with_java

This is a necessary evil for cases where bridgesupport does the wrong thing, or if you have to override constructors.

**Comment by GantMan** [comment]
For a moment there, I thought this was the ability to include raw .java.   Yes I remember this... it's a necessary evil.

I spoke with Joffrey recently, and he'll be working in a way to include .java files via gradle soon.

**Comment by jamonholmgren** [comment]
That's interesting, @darinwilson . You can also include other methods, not just constructors?

**Comment by darinwilson** [comment]
Yep - it can be anything. It's just copied wholesale into the generated Java class.

**Comment by darinwilson** [comment]
So, who do you have to know to get a merge around this place? ;)

**Comment by skellock** [comment]
Sorry Darin.

**Pull request merged**
