### PR TITLE
Faster styling

### PR DESCRIPTION
**Pull request by skellock**
**a morning sun rises over a mountain peak**

From the keyboard of @twerth 

**cut to a tight closeup of the feet of a small child running**

comes a coming-of-age story...

**queue any song by Coldplay**

of an unlikely styler...who dared to be...

**stop music, fade to black, heartbeat sounds**

faster.

### CODE REVIEW

**Comment by KCErb** [comment]
free time + iMovie  = 

https://www.youtube.com/watch?v=xI6l6ydnjGM

**Comment by skellock** [comment]
The movie is private.... lemme see lemme see!!!

**Comment by KCErb** [comment]
Oops, fixed now?

**Comment by skellock** [comment]
For your outstanding commitment to bring my lame joke to the next level, I award you: the Internet Medal of Honour.

Well done stranger.  Well done.

**Comment by darinwilson** [comment]
⭐️⭐️⭐️⭐️⭐️

**Comment by jamonholmgren** [comment]
Freaking awesome.

**Comment by twerth** [comment]
So strange, so awesome!

**Comment by carlinisaacson** [comment]
@KCErb 

You sir, deserve an upvote!

10/5

**Comment by GantMan** [comment]
@skellock wasted his last wish on this.   @KCErb disappears back into a lamp that fades away in his hands.

**Comment by KCErb** [comment]
Anything to procrastinate writing my first paper



:sigh: gradschool

**Pull request merged**
