### PR TITLE
Much better action bar and back button handling

### PR DESCRIPTION
**Pull request by jamonholmgren**
You can now do this:

```ruby
class MyScreen < PMScreen
  action_bar true, back: true

end
```

When you open/close a screen, it'll automatically show or hide the action bar and the back button. Defaults to true/true.

@twerth

### CODE REVIEW

**Comment by jamonholmgren** [comment]
I also fixed a bug with the PMNavigationActivity where hitting the device back button would show an empty activity once you had popped all the fragments off the stack.

**Comment by jamonholmgren** [comment]
Also added another hook:

```ruby
def on_back_selected(item)
  super # will close the current screen
  # or do custom logic here, like a confirm dialog
  SomeAlert.confirm "Are you sure?" do |yesno|
    super if yesno == "yes"
  end
end
```

**Comment by jamonholmgren** [comment]
I wonder if we should change the hook to `on_back_pressed` and capture the OS back button too.

**Comment by twerth** [comment]
should I merge this?

**Comment by jamonholmgren** [comment]
Should be good to go!

**Pull request merged**
