### PR TITLE
Added ability to close to previous screen

### PR DESCRIPTION
**Pull request by jamonholmgren**
So, @GantMan and @darinwilson and @leonskim and I worked on this one for quite a while. The upshot is that you need to provide a custom activity if you want to use `close to_screen`.

```ruby
class MyActivity < PMSingleFragmentActivity
end

# ...
open MyScreen, activity: MyActivity

# ...
close to_screen: MyScreen, activity: MyActivity
```

If you don't provide an activity both when you open the screen and when you close to it, it won't work.

### CODE REVIEW

**Comment by GantMan** [comment]
Dude you got it!?  Awesome!

**Comment by jamonholmgren** [comment]
Yeah, it works!

**Comment by darinwilson** [comment]
Nice work!

**Comment by jamonholmgren** [comment]
Mergable?

**Pull request closed without merging**
