### PR TITLE
Added "open" to the REPL

### PR DESCRIPTION
**Pull request by jamonholmgren**
In REPL:

screen shot 2015-06-02 at 2 15 15 pm

Makes it easier to work on screens. Just `open MyScreen` and you see it.

(Tested and does work)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Do you think adding `open` to every object could be problematic? Do you know a better way to add something to REPL?

**Comment by GantMan** [comment]
Does this align with ProMotion?   It's not much to simply call `rmq.screen.open` if that's what one wants.   Or even `app.open` would be better.

**Comment by jamonholmgren** [comment]
app.open is a good idea.

**Comment by jamonholmgren** [comment]
I don't really have any REPL helpers in ProMotion, so this is more of a *Potion thing.

**Comment by jamonholmgren** [comment]
Going to rethink this.

**Comment by twerth** [comment]
open is on screens

By default REPL is in Activity

`find.screen.open`

**Pull request closed without merging**
